# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

logger:
  default: info
  logs:
    homeassistant.components.mysensors: info
    mysensors: info
    homeassistant.components.automation: info

recorder:
  auto_purge: true
  purge_keep_days: 10

http:
  use_x_forwarded_for: True
  trusted_proxies: !secret IP_bastion

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

# Text to speech
tts:
  - platform: google_translate
    language: "fr"
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say

#zwave:
#usb_path: '/dev/ttyAMA0'
#device_config: !include zwave_device_config.yaml

media_player:
  - platform: yamaha_musiccast
    host: !secret IP_yamaha_musiccast
  - platform: androidtv
    host: !secret IP_androidtv
    name: "MiBox"
    device_class: androidtv
    apps:
      com.netflix.ninja: "Netflix"
      tv.molotov.app: "Molotov"

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_key

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

huawei_lte:
  - url: !secret HuaweiURL
    password: !secret HuaweiPassword

tplink_lte:
  - host: !secret TPLinkURL
    password: !secret TPlinkPassword

android_ip_webcam:
  #- host: !secret android_lg_g2
  #  port: 8000
  #  name: android_lg_g2
  #  sensors:
  #    - battery_level
  #    - battery_temp
  #    - battery_voltage
  #    - light
  #    - motion
  #    - proximity
  #  switches:
  #    - ffc
  #    - night_vision
  #    - focus
  #    - torch
  - host: !secret android_htc
    port: 8080
    name: android_htc

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  tags_attributes:
    - friendly_name
  # include:
  #   entity_globs:
  #     - sensor.temperature*
  #     - sensor.humidity*
  #     - sensor.pressure*
  #     - binary_sensor.door*
  #     - sensor.huawei*
  #   domains:
  #     - weather
  #     - sun

  #panel_iframe:
# router:
#   title: 'Octoprint'
#   url: 'http://192.168.1.***:5000'
#   icon: 'mdi:printer-3d'

# pi_hole:
#   - host: !secret pihole_hebergnity_ip
#     name: PiHole Hebergnity
#   - host: !secret pihole_ip
#     name: PiHole
#     api_key: !secret pihole_api

#image_processing:
#  - platform: opencv
#    source:
#      - entity_id: camera.camera_interieure_profile000_mainstream
#    classifier:
#      mom: /config/OpenCV/haarcascade_fullbody.xml

