#####################
## Xiaomi MI FLora ##
#####################

- platform: miflora
  mac: !secret MAC_miflora

########################
## Test MQTT ##
########################

- platform: mqtt
  name: "test camera motion"
  state_topic: "CAM_SUD"
