vacuum:
  - platform: xiaomi_miio
    host: !secret IP_xiaomi_miio
    token: !secret xiaomi_vacuum_token
    name: Aspirateur_Robot

########################
## Gestion aspirateur ##
########################
script:
  vacuum_vidage_bac:
    alias: Vacuum vidage bac
    sequence:
      - service: vacuum.stop
        data:
          entity_id: vacuum.aspirateur_robot
      - service: vacuum.send_command
        data:
          entity_id: vacuum.aspirateur_robot
          command: app_goto_target
          params: [20250, 20700]
      - service: input_number.set_value
        data_template:
          entity_id: input_number.xiaomi_vacuum_dernier_vidage
          value: "{{state_attr('vacuum.aspirateur_robot', 'total_cleaned_area')}}"
  "1590126423860":
    alias: Aspirateur_Reset_Carte
    sequence:
      - data: {}
        entity_id: vacuum.aspirateur_robot
        service: vacuum.start
      - delay: 00:05
      - data: {}
        entity_id: vacuum.aspirateur_robot
        service: vacuum.stop
      - data: {}
        entity_id: vacuum.aspirateur_robot
        service: vacuum.return_to_base
automation:
  - alias: Aspirateur vérification fréquence vidage
    trigger:
      platform: template
      value_template: "{{ is_state_attr('vacuum.aspirateur_robot', 'status', 'Charging') }}"
    condition:
      condition: template
      value_template: "{{(state_attr('vacuum.aspirateur_robot', 'total_cleaned_area') | float - states('input_number.xiaomi_vacuum_dernier_vidage') | float) > states('input_number.xiaomi_vacuum_frequence_vidage') | float}}"
    action:
      service: script.vacuum_vidage_bac

input_number:
  xiaomi_vacuum_dernier_vidage:
    min: 0
    max: 9999999
  xiaomi_vacuum_frequence_vidage:
    name: Fréquence vidage bac
    min: 0
    max: 500
    mode: slider
    step: 10
  xiaomi_vacuum_map_rotation:
    name: Rotation carte aspirateur
    mode: slider
    initial: 0
    min: -180
    max: 180
    step: 90

camera:
  - platform: xiaomi_cloud_map_extractor
    country: "cn"
    name: "My Vacuum Camera"
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    colors:
      color_map_inside: [32, 115, 185]
      color_map_outside: [19, 87, 148]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [93, 109, 126]
      color_grey_wall: [93, 109, 126]
      color_path: [147, 194, 238]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [75, 235, 149]
      color_unknown: [0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
    # room_colors:
    #   1: [240, 178, 122]
    #   2: [133, 193, 233]
    #   3: [217, 136, 128]
    #   4: [52, 152, 219]
    #   5: [205, 97, 85]
    #   6: [243, 156, 18]
    #   7: [88, 214, 141]
    #   8: [245, 176, 65]
    #   9: [252, 212, 81]
    #   10: [72, 201, 176]
    #   11: [84, 153, 199]
    #   12: [133, 193, 233]
    #   13: [245, 176, 65]
    #   14: [82, 190, 128]
    #   15: [72, 201, 176]
    #   16: [165, 105, 18]
    draw:
      - charger
      - path
      - goto_path
      - predicted_path
      - no_go_zones
      - no_mopping_zones
      - vacuum_position
      - virtual_walls
      - zones
    # texts:
    #   - text: "Room 1"
    #     x: 25
    #     y: 25
    #     color: [125, 20, 213]
    #   - text: "Room 2"
    #     x: 25
    #     y: 75
    #     color: [125, 20, 213, 127]
    #     font: "FreeSans.ttf"
    #     font_size: 25
    map_transformation:
      #   scale: 2
      rotate: 90
    #   trim:
    #     top: 10
    #     bottom: 20
    #     left: 30
    #     right: 40
    sizes:
      charger_radius: 4
      vacuum_radius: 4
    attributes:
      - calibration_points
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    scan_interval:
      seconds: 60
    auto_update: true
    # store_map: true

sensor:
  - platform: template
    sensors:
      vacuum_battery:
        unit_of_measurement: "%"
        value_template: "{{ state_attr('vacuum.aspirateur_robot', 'battery_level') }}"
        icon_template: mdi:battery
        device_class: battery
      vacuum_status:
        value_template: "{{ states.vacuum.aspirateur_robot.attributes.status }}"
      vacuum_main_brush:
        value_template: "{{ states.vacuum.aspirateur_robot.attributes.main_brush_left }}"
        unit_of_measurement: "h"
      vacuum_side_brush:
        value_template: "{{ states.vacuum.aspirateur_robot.attributes.side_brush_left }}"
        unit_of_measurement: "h"
      vacuum_filter:
        value_template: "{{ states.vacuum.aspirateur_robot.attributes.filter_left }}"
        unit_of_measurement: "h"
      vacuum_sensor:
        value_template: "{{ states.vacuum.aspirateur_robot.attributes.sensor_dirty_left }}"
        unit_of_measurement: "h"
      vacuum_fan_speed:
        value_template: "{{ states.vacuum.aspirateur_robot.attributes.fan_speed }}"
        unit_of_measurement: "%"
      vacuum_remplissage_bac:
        value_template: "{{((state_attr('vacuum.aspirateur_robot', 'total_cleaned_area') | float - states('input_number.xiaomi_vacuum_dernier_vidage') | float)/states('input_number.xiaomi_vacuum_frequence_vidage') | float * 100 )| round(0) }}"
        unit_of_measurement: "%"
#      vacuum_last_trash:
#        value_template: 0
#        unit_of_measurement: 'h'
